spring.datasource.url=jdbc:mysql://localhost:3306/jobportal_db
spring.datasource.username=root
spring.datasource.password=Saikumarch0909@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081